version: 2.1
orbs:
  node: circleci/node@4.0.0
executors:
  docker-executor:
    # for docker you must specify an image to use for the primary container
    docker:
      - image: circleci/node:12.18.3
jobs:
  build:
    # Each job must declare an executor
    executor: docker-executor
    steps:
      - checkout
      - run: yarn deps
      - run: pwd
      - run: ls -la
      - run:
          name: lint backend and frontend
          command: yarn run lint:ci && cd frontend && yarn run lint:ci
      - store_artifacts:
          path: reports/lint/
      - store_artifacts:
          path: frontend/reports/lint/
  test:
    executor: docker-executor
    steps:
      - run: pwd
      - run: ls -la
      - run:
          name: test backend and frontend
          command: yarn run test:ci && cd frontend && yarn run test:ci
      - store_test_results:
          path: reports/test/
      - store_test_results:
          path: frontend/reports/test/
workflows:
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
