version: 2.1
orbs:
  node: circleci/node@4.0.0
executors:
  docker-executor:
    # for docker you must specify an image to use for the primary container
    docker:
      - image: circleci/node:12.18
        environment:
          DATABASE_URL: postgresql://postgres@localhost/ttasmarthub
      - image: circleci/postgres:12.4-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secretpass
          POSTGRES_DB: ttasmarthub
commands:
  create_combined_yarnlock:
    description: "Concatenate all yarn.json files into single file.
      File is used as checksum source for part of caching key."
    parameters:
      filename:
        type: string
        default: "combined-yarnlock.txt"
    steps:
      - run:
          name: Combine package-lock.json files to single file
          command: cat yarn.lock frontend/yarn.lock > << parameters.filename >>
parameters:
  cg_org:
    description: "Cloud Foundry cloud.gov organization name"
    default: "hhs-acf-prototyping"
    type: string
  cg_api:
    description: "URL of Cloud Controller in Cloud Foundry cloud.gov instance"
    default: "https://api.fr.cloud.gov"
    type: string
  prod_git_url:
    description: "URL of github repo that will deploy to prod"
    default: "https://github.com/HHS/Head-Start-TTADP"
    type: string
  staging_git_url:
    description: "URL of github repo that will deploy to staging"
    default: "https://github.com/HHS/Head-Start-TTADP"
    type: string
  dev_git_url:
    description: "URL of github repo that will deploy to dev"
    default: "https://github.com/adhocteam/Head-Start-TTADP"
    type: string
  prod_git_branch:
    description: "name of branch that will deploy to prod"
    default: "production"
    type: string
  staging_git_branch:
    description: "name of branch that will deploy to staging"
    default: "main"
    type: string
  dev_git_branch:
    description: "name of branch that will deploy to dev"
    default: "main"
    type: string
  sandbox_git_branch:  # this will be removed before PR#23 is merged
    default: "sj-cd-init"
    type: string
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - create_combined_yarnlock
      - restore_cache:
          keys:
            # To manually bust the cache, increment the version numbers e.g. v2-yarn...
            - v1-yarn-deps-{{ checksum "combined-yarnlock.txt" }}
            # If checksum is new, restore partial cache
            - v1-yarn-deps-
      - run: yarn deps
      - save_cache:
          paths:
            - combined-yarnlock.txt
          key: v1-yarn-deps-{{ checksum "combined-yarnlock.txt" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint backend and frontend
          command: yarn run lint:ci && cd frontend && yarn run lint:ci
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: frontend/reports
  test_backend:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run migrations ci
          command: yarn run db:migrate:ci
      - run:
          name: Test backend
          command: yarn run test:ci
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: coverage/
  test_frontend:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test frontend
          command: cd frontend && yarn run test:ci
      - store_test_results:
          path: frontend/reports/
      - store_artifacts:
          path: frontend/coverage/
  deploy:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build backend assets
          command: yarn build
      - run:
          name: Build frontend assets
          command: cd frontend && yarn build
      - run: curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
      - run: sudo dpkg -i cf-cli_amd64.deb
      - when:  # sandbox - this will be removed before PR#23 is merged
          condition:
            and:
              - equal: [<< pipeline.project.git_url >>, << pipeline.parameters.dev_git_url >>]
              - equal: [<< pipeline.git.branch >>, << pipeline.parameters.sandbox_git_branch >>]
          steps:
            - run:
                name: Login with service account
                command: cf login -a << pipeline.parameters.cg_api >> -u $CLOUDGOV_SANDBOX_USERNAME -p $CLOUDGOV_SANDBOX_PASSWORD -o << pipeline.parameters.cg_org >> -s ohstta-sandbox
            - run:
                name: Push application with sandbox vars
                command: cf push --vars-file deployment_config/dev_vars.yml
      - when:  # dev
          condition:
            and:
              - equal: [<< pipeline.project.git_url >>, << pipeline.parameters.dev_git_url >>]
              - equal: [<< pipeline.git.branch >>, << pipeline.parameters.dev_git_branch >>]
          steps:
            - run:
                name: Login with service account
                command: cf login -a << pipeline.parameters.cg_api >> -u $CLOUDGOV_DEV_USERNAME -p $CLOUDGOV_DEV_PASSWORD -o << pipeline.parameters.cg_org >> -s $CLOUDGOV_DEV_SPACE
            - run:
                name: Push application with dev vars
                command: cf push --vars-file deployment_config/dev_vars.yml
      - when:  # staging
          condition:
            and:
              - equal: [<< pipeline.project.git_url >>, << pipeline.parameters.staging_git_url >>]
              - equal: [<< pipeline.git.branch >>, << pipeline.parameters.staging_git_branch >>]
          steps:
            - run:
                name: Login with service account
                command: cf login -a << pipeline.parameters.cg_api >> -u $CLOUDGOV_STAGING_USERNAME -p $CLOUDGOV_STAGING_PASSWORD -o << pipeline.parameters.cg_org >> -s $CLOUDGOV_STAGING_SPACE
            - run:
                name: Push application with staging vars
                command: cf push --vars-file deployment_config/staging_vars.yml
      - when:  # prod
          condition:
            and:
              - equal: [<< pipeline.project.git_url >>, << pipeline.parameters.prod_git_url >>]
              - equal: [<< pipeline.git.branch >>, << pipeline.parameters.prod_git_branch >>]
          steps:
            - run:
                name: Login with service account
                command: cf login -a << pipeline.parameters.cg_api >> -u $CLOUDGOV_PROD_USERNAME -p $CLOUDGOV_PROD_PASSWORD -o << pipeline.parameters.cg_org >> -s $CLOUDGOV_PROD_SPACE
            - run:
                name: Push application with prod vars
                command: cf push --vars-file deployment_config/prod_vars.yml
workflows:
  build_test_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test_backend:
          requires:
            - build
      - test_frontend:
          requires:
            - build
      - deploy:
          requires:
            - build
            - lint
            - test_backend
            - test_frontend
          filters:
            branches:
              only:
                - << pipeline.parameters.sandbox_git_branch >>  # this will be removed before PR#23 is merged
                - << pipeline.parameters.dev_git_branch >>
                - << pipeline.parameters.staging_git_branch >>
                - << pipeline.parameters.prod_git_branch >>
