version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build_and_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn deps
      - run: yarn run lint:ci
      - store_artifacts:
          path: reports
      - run: yarn run test:ci
      - store_test_results:
          path: reports
