version: 2.1
orbs:
  node: circleci/node@4.0.0
executors:
  docker-executor:
    # for docker you must specify an image to use for the primary container
    docker:
      - image: circleci/node:12.18.3
jobs:
  build:
    # Each job must declare an executor
    executor: docker-executor
    steps:
      - checkout
      - run: yarn deps
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint_backend_and_frontend:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint backend and frontend
          command: yarn run lint:ci && cd frontend && yarn run lint:ci
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: frontend/reports
  test_backend:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test backend
          command: yarn run test:ci
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: coverage/
  test_frontend:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test frontend
          command: cd frontend && yarn run test:ci
      - store_test_results:
          path: frontend/reports/
      - store_artifacts:
          path: frontend/coverage/
  deploy_dev:
    filters:
      branches:
        only:  # only branches matching the below regex filters will run
          - /sj-cd-init*/
    executor: docker-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo $MY_FAKE_ENV_VAR

workflows:
  build_and_test:
    jobs:
      - build
      - lint_backend_and_frontend:
          requires:
            - build
      - test_backend:
          requires:
            - build
      - test_frontend:
          requires:
            - build
      - deploy_dev:
          requires:
            - lint_backend_and_frontend
            - test_backend
            - test_frontend
