version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run: yarn deps
      # lint and test backend
      - run: yarn run lint:ci && yarn run test:ci
      - store_artifacts:
          path: reports/lint/
      - store_test_results:
          path: reports/test/
      # lint and test frontend
      - run: cd frontend && yarn run lint:ci && yarn run test:ci && cd ..
      - store_artifacts:
          path: frontend/reports/lint/
          destination: reports/lint/
      - store_test_results:
          path: frontend/reports/test/
          destination: reports/test/
